// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcr4CSVq2cFtSYX2wwJhjEqmBDx197HDc',
    appId: '1:1023024144257:web:699af50268c545994c5280',
    messagingSenderId: '1023024144257',
    projectId: 'recipe-app-17ffd',
    authDomain: 'recipe-app-17ffd.firebaseapp.com',
    databaseURL: 'https://recipe-app-17ffd-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-app-17ffd.appspot.com',
    measurementId: 'G-0H4XX49NFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJn3jvXB3MWQ03X3wMhPnbQTx9-Mkl6oo',
    appId: '1:1023024144257:android:8efe8c476434e4124c5280',
    messagingSenderId: '1023024144257',
    projectId: 'recipe-app-17ffd',
    databaseURL: 'https://recipe-app-17ffd-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-app-17ffd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYWhTN4EbrBBWAICBs0BGNCRDWHx_EuaI',
    appId: '1:1023024144257:ios:00252965155c717b4c5280',
    messagingSenderId: '1023024144257',
    projectId: 'recipe-app-17ffd',
    databaseURL: 'https://recipe-app-17ffd-default-rtdb.firebaseio.com',
    storageBucket: 'recipe-app-17ffd.appspot.com',
    iosBundleId: 'com.example.recipeApp',
  );
}
